name: Release

run-name: bump ${{ inputs.version }} version by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'part of the project version to update'
        options:
        - major
        - minor
        - patch
        required: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ needs.release.outputs.tag }}

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Configure git
        env:
          MEX_BOT_EMAIL: ${{ vars.MEX_BOT_EMAIL }}
          MEX_BOT_USER: ${{ vars.MEX_BOT_USER }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PUB: ${{ secrets.SIGNING_PUB }}
        run: |
          eval "$(ssh-agent -s)"
          pdm setup-commit-signing

      - name: Release new version
        id: release
        run: |
          pdm release ${{ inputs.version }}
          echo "tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"

  distribute:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    environment:
      name: pypi
      url: https://pypi.org/p/mex-model
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ needs.release.outputs.tag }}
          persist-credentials: false

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          make setup
          sudo apt-get install -y gettext

      - name: Compile translation *.po files to *.mo
        run: |
          find mex/model/i18n -type f -name "*.po" | while read -r po_file; do
            mo_file="${po_file%.po}.mo"
            echo "Compiling $po_file → $mo_file"
            msgfmt "$po_file" -o "$mo_file"
          done

      - name: Build wheel and sdist distros and create a github release
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          gh release create ${{ needs.release.outputs.tag }} --generate-notes --latest --verify-tag
          pdm build --dest dist
          for filename in dist/*; do
            gh release upload ${{ needs.release.outputs.tag }} ${filename};
          done

      - name: Create schema.zip file and add to github release
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          PDM_CHECK_UPDATE: False
        run: |
          pdm run python scripts/build_schema_zip.py
          gh release upload ${{ needs.release.outputs.tag }} schema.zip

#      - name: Publish distribution 📦 to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
